### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by bahlo** [fastbill/go-httperrors#2]
As seen in the [reddit thread](https://www.reddit.com/r/golang/comments/8g8zoa/httperrors_elegant_http_error_handling/) the README could use some love, i.e.:

* Explain the difference to `echo.HTTPError`
* Explain why [this rule](https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully) doesn't really apply

**Comment by junedev** [comment]
Readme changed, more explanation added, closing this for now.
